import { NetflixDataResponse, NewsDataResponse, EventsDataResponse } from '../types';

export const FALLBACK_NETFLIX_DATA: Record<string, NetflixDataResponse> = {
  default: {
    week: 'Recent',
    category: 'Films',
    country: 'India',
    cached: true,
    lastUpdated: new Date().toISOString(),
    movies: [
      {
        rank: 1,
        title: 'Vishwanath & Sons',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 2,
        change: 'same',
        releaseYear: '2026',
        overview: 'A poignant, heartwarming drama following three generations of a traditional textile family navigating ambition, tradition, and modern crossroads.',
        netflixUrl: 'https://www.netflix.com/search?q=Vishwanath',
        posterUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 2,
        title: 'Dhamaal 4',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 3,
        change: 'up',
        rankChange: 1,
        releaseYear: '2026',
        overview: 'The beloved eccentric group of adventurers embark on another chaotic cross-country treasure hunt fraught with hilarious misadventures and wild encounters.',
        netflixUrl: 'https://www.netflix.com/search?q=Dhamaal',
        posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 3,
        title: 'GDN: The Flying Machine',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 2,
        change: 'same',
        releaseYear: '2026',
        overview: 'An inspiring biographical saga celebrating the vision of pioneer inventor G.D. Naidu, known as the Edison of India, and his breakthroughs in mechanical design.',
        netflixUrl: 'https://www.netflix.com/search?q=GDN',
        posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 4,
        title: 'Gandhari',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 2,
        change: 'down',
        rankChange: 1,
        releaseYear: '2026',
        overview: 'A fierce mother with a mysterious past embarks on a relentless quest across treacherous terrains to rescue her abducted child against all odds.',
        netflixUrl: 'https://www.netflix.com/search?q=Gandhari',
        posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 5,
        title: 'Alpha',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 4,
        change: 'same',
        releaseYear: '2026',
        overview: 'A high-octane spy thriller featuring elite secret intelligence operatives unraveling a global syndicate threatening sovereign cybersecurity.',
        netflixUrl: 'https://www.netflix.com/search?q=Alpha',
        posterUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 6,
        title: 'Newton’s 3rd Law',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 3,
        change: 'up',
        rankChange: 2,
        releaseYear: '2026',
        overview: 'Every action has an equal and opposite reaction: an edge-of-the-seat courtroom thriller exploring whistleblowers and corporate accountability.',
        netflixUrl: 'https://www.netflix.com/search?q=Newton',
        posterUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 7,
        title: 'Cocktail 2',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 5,
        change: 'down',
        rankChange: 1,
        releaseYear: '2026',
        overview: 'A modern tale of friendship, tangled romance, and career dilemmas set against the vibrant backdrops of London and Mumbai.',
        netflixUrl: 'https://www.netflix.com/search?q=Cocktail',
        posterUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 8,
        title: 'Pyaar Prema Kalyanam',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 4,
        change: 'same',
        releaseYear: '2026',
        overview: 'A delightful romantic comedy about two contrasting families trying to organize the wedding of the year without letting ancient rivalries boil over.',
        netflixUrl: 'https://www.netflix.com/search?q=Pyaar+Prema',
        posterUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 9,
        title: 'Gatta Kusthi 2',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 7,
        change: 'down',
        rankChange: 2,
        releaseYear: '2026',
        overview: 'The beloved wrestling couple returns to take on international championship bouts while balancing neighborhood politics and family expectations.',
        netflixUrl: 'https://www.netflix.com/search?q=Gatta+Kusthi',
        posterUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&auto=format&fit=crop&q=80',
      },
      {
        rank: 10,
        title: 'Korean Kanakaraju',
        category: 'Films',
        type: 'Movie',
        cumulativeWeeks: 2,
        change: 'new',
        releaseYear: '2026',
        overview: 'A hilarious cross-cultural caper about a humble Indian culinary enthusiast who accidentally finds himself in Seoul competing in a street-food championship.',
        netflixUrl: 'https://www.netflix.com/search?q=Kanakaraju',
        posterUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&auto=format&fit=crop&q=80',
      },
    ],
  },
};

export interface PrimeMovie {
  rank: number;
  title: string;
  seasonTitle?: string;
  category: string;
  type: 'Series' | 'Movie';
  rating?: string;
  releaseYear: string;
  overview: string;
  primeUrl: string;
  posterUrl: string;
}

export const AMAZON_PRIME_INDIA_DATA: {
  series: PrimeMovie[];
  movies: PrimeMovie[];
} = {
  series: [
    {
      rank: 1,
      title: 'Mirzapur',
      seasonTitle: 'Season 3',
      category: 'TV',
      type: 'Series',
      rating: '8.5/10 IMDb',
      releaseYear: '2024-2026',
      overview: 'The iron-fisted Akhandanand Tripathi rules the Purvanchal mafia, but an explosive feud with Guddu Pandit plunges Mirzapur into a ruthless battle for the throne.',
      primeUrl: 'https://www.primevideo.com/detail/Mirzapur',
      posterUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 2,
      title: 'Panchayat',
      seasonTitle: 'Season 3',
      category: 'TV',
      type: 'Series',
      rating: '8.9/10 IMDb',
      releaseYear: '2024-2026',
      overview: 'An engineering graduate takes on the role of a Panchayat secretary in the remote village of Phulera, navigating eccentric village politics and local bonds.',
      primeUrl: 'https://www.primevideo.com/detail/Panchayat',
      posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 3,
      title: 'The Family Man',
      seasonTitle: 'Season 2',
      category: 'TV',
      type: 'Series',
      rating: '8.7/10 IMDb',
      releaseYear: '2024',
      overview: 'Srikant Tiwari, a middle-class intelligence operative for TASC, desperately juggles defending the nation from terror plots with secret suburban dad duties.',
      primeUrl: 'https://www.primevideo.com/detail/The-Family-Man',
      posterUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 4,
      title: 'Farzi',
      seasonTitle: 'Season 1',
      category: 'TV',
      type: 'Series',
      rating: '8.4/10 IMDb',
      releaseYear: '2024',
      overview: 'A brilliant disillusioned street artist designs the ultimate counterfeit currency note, drawn into a high-stakes cat-and-mouse hunt with a fiery task force officer.',
      primeUrl: 'https://www.primevideo.com/detail/Farzi',
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 5,
      title: 'Paatal Lok',
      seasonTitle: 'Season 1 & 2',
      category: 'TV',
      type: 'Series',
      rating: '8.1/10 IMDb',
      releaseYear: '2025',
      overview: 'A cynical Delhi cop lands the case of a lifetime investigating a foiled assassination attempt on a prominent prime-time anchor, descending into the dark underworld.',
      primeUrl: 'https://www.primevideo.com/detail/Paatal-Lok',
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 6,
      title: 'Dahaad',
      seasonTitle: 'Season 1',
      category: 'TV',
      type: 'Series',
      rating: '7.8/10 IMDb',
      releaseYear: '2024',
      overview: 'Sub-inspector Anjali Bhaati investigates a chilling series of deaths where women are found dead in public bathrooms, uncovering a calculated serial killer.',
      primeUrl: 'https://www.primevideo.com/detail/Dahaad',
      posterUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 7,
      title: 'Jubilee',
      seasonTitle: 'Season 1',
      category: 'TV',
      type: 'Series',
      rating: '8.3/10 IMDb',
      releaseYear: '2024',
      overview: 'Set against the golden era of Hindi cinema in newly independent Bombay, exploring the ruthless ambition, poetic glamour, and betrayal behind the silver screen.',
      primeUrl: 'https://www.primevideo.com/detail/Jubilee',
      posterUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 8,
      title: 'Suzhal: The Vortex',
      seasonTitle: 'Season 1',
      category: 'TV',
      type: 'Series',
      rating: '8.2/10 IMDb',
      releaseYear: '2024',
      overview: 'In a micro-town during the mystical Mayana Kollai festival, a simple missing person case unspools deep-seated social fault lines and harrowing conspiracies.',
      primeUrl: 'https://www.primevideo.com/detail/Suzhal',
      posterUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 9,
      title: 'Bandish Bandits',
      seasonTitle: 'Season 2',
      category: 'TV',
      type: 'Series',
      rating: '8.6/10 IMDb',
      releaseYear: '2025',
      overview: 'A classical vocal virtuoso shackled by ancient gharana discipline joins forces with an outspoken pop singer to forge an unforgettable musical revolution.',
      primeUrl: 'https://www.primevideo.com/detail/Bandish-Bandits',
      posterUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 10,
      title: 'Breathe: Into the Shadows',
      seasonTitle: 'Season 2',
      category: 'TV',
      type: 'Series',
      rating: '7.6/10 IMDb',
      releaseYear: '2024',
      overview: 'A desperate psychiatrist is blackmailed into executing serial murders to save his kidnapped daughter, hunted relentlessly by Kabir Sawant.',
      primeUrl: 'https://www.primevideo.com/detail/Breathe',
      posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&auto=format&fit=crop&q=80',
    },
  ],
  movies: [
    {
      rank: 1,
      title: 'Kantara: A Legend',
      category: 'Films',
      type: 'Movie',
      rating: '8.3/10 IMDb',
      releaseYear: '2024',
      overview: 'When human greed ignites a conflict between villagers and the forest department, a rebel champion is possessed by the sacred guardian spirit of Panjurli Daiva.',
      primeUrl: 'https://www.primevideo.com/detail/Kantara',
      posterUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 2,
      title: 'K.G.F: Chapter 2',
      category: 'Films',
      type: 'Movie',
      rating: '8.3/10 IMDb',
      releaseYear: '2024',
      overview: 'Rocky reigns supreme over the blood-soaked Kolar Gold Fields, facing off against the formidable warlord Adheera and government forces.',
      primeUrl: 'https://www.primevideo.com/detail/KGF-Chapter-2',
      posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 3,
      title: 'Jai Bhim',
      category: 'Films',
      type: 'Movie',
      rating: '8.8/10 IMDb',
      releaseYear: '2023',
      overview: 'A fearless advocate fights for a desperate tribal woman whose husband was unlawfully detained and went missing from police custody.',
      primeUrl: 'https://www.primevideo.com/detail/Jai-Bhim',
      posterUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 4,
      title: 'Shershaah',
      category: 'Films',
      type: 'Movie',
      rating: '8.4/10 IMDb',
      releaseYear: '2023',
      overview: 'The heroic, inspiring journey of Param Vir Chakra awardee Captain Vikram Batra during the 1999 Kargil War.',
      primeUrl: 'https://www.primevideo.com/detail/Shershaah',
      posterUrl: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 5,
      title: 'Sardar Udham',
      category: 'Films',
      type: 'Movie',
      rating: '8.4/10 IMDb',
      releaseYear: '2023',
      overview: 'A deeply poignant biographical chronicle of revolutionary freedom fighter Udham Singh, who assassinated Michael O’Dwyer in London to avenge the Jallianwala Bagh massacre.',
      primeUrl: 'https://www.primevideo.com/detail/Sardar-Udham',
      posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 6,
      title: 'Ponniyin Selvan: Part 2',
      category: 'Films',
      type: 'Movie',
      rating: '7.8/10 IMDb',
      releaseYear: '2024',
      overview: 'Mani Ratnam’s grand cinematic climax follows Arulmozhi Varman continuing his destiny to become Rajaraja Chola I amid court intrigues and battlefields.',
      primeUrl: 'https://www.primevideo.com/detail/Ponniyin-Selvan-2',
      posterUrl: 'https://images.unsplash.com/photo-1570784332176-fdd73da66f03?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 7,
      title: 'Varisu',
      category: 'Films',
      type: 'Movie',
      rating: '7.2/10 IMDb',
      releaseYear: '2024',
      overview: 'The prodigal son returns to take over his father’s sprawling business empire and heal fractured family dynamics while fending off corporate rivals.',
      primeUrl: 'https://www.primevideo.com/detail/Varisu',
      posterUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 8,
      title: 'Soorarai Pottru',
      category: 'Films',
      type: 'Movie',
      rating: '8.7/10 IMDb',
      releaseYear: '2023',
      overview: 'A passionate former Air Force captain dreams of launching a low-cost airline so everyday working-class Indians can afford to fly.',
      primeUrl: 'https://www.primevideo.com/detail/Soorarai-Pottru',
      posterUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 9,
      title: 'Pushpa: The Rise',
      category: 'Films',
      type: 'Movie',
      rating: '7.6/10 IMDb',
      releaseYear: '2023',
      overview: 'Pushpa Raj, a red sandalwood laborer in the Seshachalam forests, rises through the syndicates with sheer grit and swagger.',
      primeUrl: 'https://www.primevideo.com/detail/Pushpa',
      posterUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=400&auto=format&fit=crop&q=80',
    },
    {
      rank: 10,
      title: 'Kantara: A Legend',
      category: 'Films',
      type: 'Movie',
      rating: '8.3/10 IMDb',
      releaseYear: '2024',
      overview: 'The explosive folklore journey showcasing the divine Kola rituals of coastal Karnataka.',
      primeUrl: 'https://www.primevideo.com/detail/Kantara',
      posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80',
    },
  ],
};

export const FALLBACK_NEWS_DATA: Record<string, NewsDataResponse> = {
  default: {
    category: 'AI & Technology',
    cached: true,
    lastUpdated: new Date().toISOString(),
    articles: [
      {
        id: 'news-ai-1',
        title: 'Autonomous AI Reasoning Frameworks Demonstrate Human-Parity Mathematical Proof Generation',
        description: 'New multimodal neural architectures achieved unprecedented benchmarks in solving complex open problems, opening new frontiers for scientific computing.',
        source: 'BBC Technology',
        url: 'https://www.bbc.com/news/technology',
        thumbnailUrl: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=400&auto=format&fit=crop&q=80',
        publishedAt: new Date().toISOString(),
        category: 'AI & Technology',
      },
      {
        id: 'news-ai-2',
        title: 'India Semiconductor Mission Approves Three New Advanced Fabrication Facilities',
        description: 'The national semiconductor initiative expands with commercial chip foundries dedicated to mobile telecommunications, automotive electronics, and AI accelerators.',
        source: 'BBC News',
        url: 'https://www.bbc.com/news/world/asia/india',
        thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&auto=format&fit=crop&q=80',
        publishedAt: new Date(Date.now() - 3600000).toISOString(),
        category: 'India',
      },
      {
        id: 'news-ai-3',
        title: 'Global Renewable Grid Integration Surpasses 45% Milestone Across Premier Corridors',
        description: 'Next-generation battery storage systems and smart grid load balancing helped major international manufacturing centers hit clean energy targets ahead of schedule.',
        source: 'BBC Science',
        url: 'https://www.bbc.com/news/science_and_environment',
        thumbnailUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&auto=format&fit=crop&q=80',
        publishedAt: new Date(Date.now() - 7200000).toISOString(),
        category: 'World',
      },
      {
        id: 'news-ai-4',
        title: 'Digital Public Infrastructure: UPI Transactions Cross Record Peak Monthly Volume',
        description: 'Unified Payments Interface registered exponential growth in cross-border settlements and retail merchant adoptions across ASEAN and European partners.',
        source: 'Financial Wire',
        url: 'https://www.bbc.com/news/business',
        thumbnailUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400&auto=format&fit=crop&q=80',
        publishedAt: new Date(Date.now() - 10800000).toISOString(),
        category: 'India',
      },
      {
        id: 'news-ai-5',
        title: 'Deep-Space Infrared Survey Detects Organic Molecules in Interstellar Stellar Nursery',
        description: 'Astronomers using orbiting space observatories confirmed rich prebiotic chemical signatures surrounding proto-planetary disks.',
        source: 'BBC Science',
        url: 'https://www.bbc.com/news/science_and_environment',
        thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&auto=format&fit=crop&q=80',
        publishedAt: new Date(Date.now() - 14400000).toISOString(),
        category: 'Science',
      },
    ],
  },
};

export const FALLBACK_AROUND_INDIA_EVENTS: EventsDataResponse = {
  dateStr: 'September / October 2026',
  lastUpdated: new Date().toISOString(),
  cached: true,
  events: [
    {
      id: 'diwali-deepavali',
      title: 'Diwali (Festival of Lights)',
      date: 'October / November (Kartik Amavasya)',
      region: 'Pan-India',
      imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=800&auto=format&fit=crop&q=80',
      description: 'The triumph of light over darkness and knowledge over ignorance, celebrated with oil lamps (diyas), fireworks, family feasts, and prayers to Goddess Lakshmi.',
      culturalSignificance: 'Marks Lord Rama’s return to Ayodhya after 14 years of exile and the victory of Lord Krishna over Narakasura.',
      category: 'festival',
    },
    {
      id: 'navratri-durga-puja',
      title: 'Navratri & Durga Puja',
      date: 'September / October (Ashvin Month)',
      region: 'West Bengal, Gujarat, North India',
      imageUrl: 'https://images.unsplash.com/photo-1601655781320-1a13b485d957?w=800&auto=format&fit=crop&q=80',
      description: 'Nine nights dedicated to the divine feminine Shakti, culminating in Vijayadashami (Dussehra). Characterized by Garba in Gujarat and magnificent community pandals in Bengal.',
      culturalSignificance: 'Celebrates Goddess Durga slaying the buffalo demon Mahishasura, symbolizing divine cosmic justice and victory of righteousness.',
      category: 'festival',
    },
    {
      id: 'dussehra-vijayadashami',
      title: 'Dussehra (Vijayadashami)',
      date: 'Tenth day of Ashvin (October)',
      region: 'Pan-India, Mysuru, Himachal Pradesh',
      imageUrl: 'https://images.unsplash.com/photo-1570784332176-fdd73da66f03?w=800&auto=format&fit=crop&q=80',
      description: 'Effigies of Ravana are burned with fireworks across northern towns, while Mysuru Palace witnesses grand royal processions.',
      culturalSignificance: 'Honors the victory of Lord Rama over Ravana, teaching the eternal truth of dharma over adharma.',
      category: 'festival',
    },
    {
      id: 'karwa-chauth',
      title: 'Karwa Chauth',
      date: 'Fourth day after Sharad Purnima (October)',
      region: 'North & Western India',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
      description: 'A traditional day-long fast observed from sunrise until the moon is sighted through a sieve, praying for longevity and health of spouses.',
      culturalSignificance: 'Strengthens family bonds, featuring henna (mehendi), festive ethnic attire, and community story-telling (Katha).',
      category: 'observance',
    },
    {
      id: 'chhath-puja',
      title: 'Chhath Puja',
      date: 'Kartik Shukla Shashthi (November)',
      region: 'Bihar, Jharkhand, Uttar Pradesh',
      imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
      description: 'An ancient Vedic ritual of rigorous fasting, standing in river waters to offer Arghya to the rising and setting Sun God (Surya).',
      culturalSignificance: 'Expresses deep gratitude to the Sun for sustaining life on Earth, celebrated for its spiritual austerity and eco-friendly rituals.',
      category: 'festival',
    },
    {
      id: 'makar-sankranti-pongal',
      title: 'Makar Sankranti / Pongal / Lohri',
      date: 'January 14–15',
      region: 'Punjab, Tamil Nadu, Gujarat, Andhra',
      imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
      description: 'The auspicious winter harvest festival marking the Sun’s transition into Capricorn. Celebrated with kite flying, bonfires, and harvested rice sweets.',
      culturalSignificance: 'Marks the end of winter solstice and the beginning of warmer days (Uttarayan), fostering community fellowship.',
      category: 'harvest',
    },
  ],
};
