import { NetflixDataResponse, NewsDataResponse } from '../types';

export const FALLBACK_NETFLIX_DATA: Record<string, NetflixDataResponse> = {
  default: {
    week: 'Recent',
    category: 'Films (English)',
    country: 'Global',
    cached: true,
    lastUpdated: new Date().toISOString(),
    movies: [
      {
        rank: 1,
        title: 'Carry-On',
        category: 'Films (English)',
        cumulativeWeeks: 4,
        change: 'same',
        overview: 'A young TSA agent fights to outsmart a mysterious traveler blackmailing him into letting a dangerous package onto a Christmas Eve flight.',
        netflixUrl: 'https://www.netflix.com/search?q=Carry-On',
      },
      {
        rank: 2,
        title: 'Glass Onion: A Knives Out Mystery',
        category: 'Films (English)',
        cumulativeWeeks: 6,
        change: 'up',
        rankChange: 1,
        overview: 'World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery involving a tech billionaire and his eclectic crew of friends.',
        netflixUrl: 'https://www.netflix.com/search?q=Glass+Onion',
      },
      {
        rank: 3,
        title: 'Leave the World Behind',
        category: 'Films (English)',
        cumulativeWeeks: 8,
        change: 'same',
        overview: "A family's quiet getaway is upended when two strangers arrive at night, bringing news of a cyberattack that grows more terrifying by the minute.",
        netflixUrl: 'https://www.netflix.com/search?q=Leave+the+World+Behind',
      },
      {
        rank: 4,
        title: 'Red Notice',
        category: 'Films (English)',
        cumulativeWeeks: 12,
        change: 'down',
        rankChange: 2,
        overview: 'An FBI profiler pursuing the world’s most wanted art thief becomes his reluctant partner in crime to catch an elusive crook who’s always one step ahead.',
        netflixUrl: 'https://www.netflix.com/search?q=Red+Notice',
      },
      {
        rank: 5,
        title: 'The Adam Project',
        category: 'Films (English)',
        cumulativeWeeks: 7,
        change: 'same',
        overview: 'After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.',
        netflixUrl: 'https://www.netflix.com/search?q=The+Adam+Project',
      },
      {
        rank: 6,
        title: 'Society of the Snow',
        category: 'Films (English)',
        cumulativeWeeks: 5,
        change: 'up',
        rankChange: 2,
        overview: 'Following a plane crash in the remote heart of the Andes, survivors join together and become each other’s best hope as they navigate their way back home.',
        netflixUrl: 'https://www.netflix.com/search?q=Society+of+the+Snow',
      },
      {
        rank: 7,
        title: 'The Gray Man',
        category: 'Films (English)',
        cumulativeWeeks: 9,
        change: 'down',
        rankChange: 1,
        overview: "When a shadowy CIA agent uncovers lethal agency secrets, he's hunted across the globe by a sociopathic rogue operative who's put a bounty on his head.",
        netflixUrl: 'https://www.netflix.com/search?q=The+Gray+Man',
      },
      {
        rank: 8,
        title: 'Don’t Look Up',
        category: 'Films (English)',
        cumulativeWeeks: 11,
        change: 'same',
        overview: 'Two astronomers go on a media tour to warn humankind of an approaching comet that will destroy Earth, but the world seems indifferent.',
        netflixUrl: 'https://www.netflix.com/search?q=Dont+Look+Up',
      },
      {
        rank: 9,
        title: 'Extraction 2',
        category: 'Films (English)',
        cumulativeWeeks: 10,
        change: 'up',
        rankChange: 1,
        overview: 'Back from the brink of death, highly skilled commando Tyler Rake takes on another dangerous mission: saving the imprisoned family of a ruthless gangster.',
        netflixUrl: 'https://www.netflix.com/search?q=Extraction+2',
      },
      {
        rank: 10,
        title: 'Enola Holmes 2',
        category: 'Films (English)',
        cumulativeWeeks: 4,
        change: 'new',
        overview: 'Now a detective-for-hire, Enola Holmes takes on her first official case to find a missing girl, as the sparks of a dangerous conspiracy ignite a mystery.',
        netflixUrl: 'https://www.netflix.com/search?q=Enola+Holmes+2',
      },
    ],
  },
};

export const FALLBACK_NEWS_DATA: Record<string, NewsDataResponse> = {
  default: {
    category: 'World',
    cached: true,
    lastUpdated: new Date().toISOString(),
    articles: [
      {
        id: 'news-fallback-1',
        title: 'Global Summit Concludes with Historic Multi-Nation Climate Resilience Accord',
        description: 'World leaders and delegates at the international summit reached a landmark agreement outlining aggressive decarbonization targets and shared clean tech funding.',
        source: 'Reuters',
        url: 'https://news.google.com',
        publishedAt: new Date(Date.now() - 3600000).toISOString(),
        category: 'World',
      },
      {
        id: 'news-fallback-2',
        title: 'Breakthrough in Clean Fusion Energy Achieved by International Physics Consortium',
        description: 'Researchers have sustained a net positive energy gain for over five consecutive minutes, marking an unprecedented milestone toward scalable clean fusion power.',
        source: 'Associated Press',
        url: 'https://news.google.com',
        publishedAt: new Date(Date.now() - 7200000).toISOString(),
        category: 'Technology',
      },
      {
        id: 'news-fallback-3',
        title: 'Global Markets Rally as Inflation Cools Across Major Economic Regions',
        description: 'Central banks express growing confidence in economic stabilization as global benchmark indices reach new yearly highs.',
        source: 'Financial Times',
        url: 'https://news.google.com',
        publishedAt: new Date(Date.now() - 10800000).toISOString(),
        category: 'Business',
      },
      {
        id: 'news-fallback-4',
        title: 'James Webb Space Telescope Discovers Atmospheric Water Vapor on Nearby Exoplanet',
        description: 'Spectroscopic analysis reveals clear chemical signatures in the habitable zone of a red dwarf star just forty light years away.',
        source: 'BBC Science',
        url: 'https://news.google.com',
        publishedAt: new Date(Date.now() - 14400000).toISOString(),
        category: 'Science',
      },
      {
        id: 'news-fallback-5',
        title: 'International Cultural Exchange Initiative Expands to 50 New Partner Cities',
        description: 'UNESCO announces new historic preservation and student innovation exchange programs connecting global metropolitan centers.',
        source: 'Global Wire',
        url: 'https://news.google.com',
        publishedAt: new Date(Date.now() - 18000000).toISOString(),
        category: 'World',
      },
    ],
  },
};

